### ISSUE TITLE
Don't use node-xml

### ISSUE THREAD

**Issue by kyunal** [fedeya/remix-sitemap#14]
**Is your feature request related to a problem? Please describe.**
Right now this library seems to use [node-xml](https://www.npmjs.com/package/xml) for XML generation. It's a very old library which is dependent on node and thus incompatible with some of Remix"s runtimes (particularly Cloudflare)

**Describe the solution you'd like**
Use a more modern XML library that is more platform agnostic, e.g. [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser)

**Describe alternatives you've considered**
Other libraries sometimes just stitch together XML strings with placeholders, but I don't think this is an ideal approach though it would keep the bundle size smaller.

**Additional context**
I'm submitting this as an issue first to spark discussion. I'd be happy to make a PR with a new library if needed once the details are settled. I think this old XML library shouldn't be used, particularly because its dependency on node contradicts some of Remix"s features and different runtimes. It would be a shame to let this go to waste.

**Comment by fedeya** [comment]
Hi @kyunal!

I selected node-xml for the low bundle thinking about platforms like cloudflare where is important not exceed the functions bundle size, but it seems to fail because it uses `stream` inside hahaha.

The package first approach strings concatenation but when google images, video and news were added the code started to look ugly.

I tried with others libraries like `json2xml` or `xmlbuilder` but i ran into some problems when i need to remove tags where the value can be optional.

I didn't know about `fast-xml-parser` but it looks great, i can try to move to that.

Also thanks for sharing this, it's very important to know if the library doesn't work correctly on some platforms!

**Comment by fedeya** [comment]
Hey @kyunal this is now available in the latest version!

**Comment by Mihai-github** [comment]
Hello everyone,

After coming across this issue, my current focus is on setting up the library locally to determine its functionality. I have a Remix.js application running on Cloudflare Pages with TurboRepo (though I'm uncertain if this detail is relevant). However, I've noticed that there's no generation of a sitemap when navigating between pages. I find myself a bit stuck at this point and unsure about the next steps to take. Your insights would be greatly appreciated.


Update: 

I see `isSitemapUrl(request)` is always `false` but not sure why:


```
const { isSitemapUrl, sitemap } = createSitemapGenerator({
    siteUrl: "http://127.0.0.1:8788/",
    // "https://" + (loadContext.env as IProcessEnv).NEXT_PUBLIC_HOSTNAME,
    generateRobotsTxt: true,
    headers: {
      "Cache-Control": "max-age=3600",
    },
  });

  if (isSitemapUrl(request)) return await sitemap(request, remixContext);
```

Also forcing the condition to run throws an error:

`Your Pages function should return a Response`
